// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdfvft1mpdWlQx8wh1D0Y7NgWNA0Crxw',
    appId: '1:848520441234:web:5620dcbf40d090cb97254b',
    messagingSenderId: '848520441234',
    projectId: 'ocsc-53e82',
    authDomain: 'ocsc-53e82.firebaseapp.com',
    databaseURL: 'https://ocsc-53e82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ocsc-53e82.firebasestorage.app',
    measurementId: 'G-5FZ18GX0GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBouuEiOChzWcpKopwVreSdHTSOarwll4I',
    appId: '1:848520441234:android:98ba5c3f4a423a6997254b',
    messagingSenderId: '848520441234',
    projectId: 'ocsc-53e82',
    databaseURL: 'https://ocsc-53e82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ocsc-53e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm763G0N690M4FH17de_4XqfrCxrScJVE',
    appId: '1:848520441234:ios:227a2b8291589fba97254b',
    messagingSenderId: '848520441234',
    projectId: 'ocsc-53e82',
    databaseURL: 'https://ocsc-53e82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ocsc-53e82.firebasestorage.app',
    iosClientId: '848520441234-en3mis5gml60p2vamg8cctgfpu013qjl.apps.googleusercontent.com',
    iosBundleId: 'com.ocsc.ocscPracticeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbGHS7xcCamw0nM01Oipo5btUya1tbKnk',
    appId: '1:848520441234:web:934fb1a354ee8eef97254b',
    messagingSenderId: '848520441234',
    projectId: 'ocsc-53e82',
    authDomain: 'ocsc-53e82.firebaseapp.com',
    databaseURL: 'https://ocsc-53e82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ocsc-53e82.firebasestorage.app',
    measurementId: 'G-R7YPTSRS1S',
  );

}